"""
MIT License

Copyright (c) 2021 Chapters

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

---
# Homepage configuration
# See https://fontawesome.com/icons for icons options
# this is an edited copy from https://github.com/bastienwirtz/homer/blob/main/public/assets/config.yml.dist
# all changes from it were made by NeverEndingChapters

title: "Pi-svr1"
subtitle: ""
logo: "raspberrypi.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Copy my Homer configat my <a href="https://github.com/NeverEndingChapters/pi-server/edit/main/Homer/config.yml">GitHub</a>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#1B998B"
    highlight-secondary: "#2E6B62"
    highlight-hover: "#74AFA2"
    background: "#2B494D"
    card-background: "#3F5458"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
#   #url: https://b4bz.io
#   style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
#   title: "Demo !"
#   icon: "fa fa-grin"
#   content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub Page"
    icon: "fab fa-github"
    url: "https://github.com/NeverEndingChapters?repositories"
    target: "_blank" # optional html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
#   - name: "another page!"
#     icon: "fas fa-file-alt"
#     url: "#additionnal-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Server Managment"
    icon: "fas fa-cloud"
    items:
      - name: "Shell In A Box"
        logo: "bash.png"
        subtitle: "WEB SHH"
        tag: "app"
        url: "https://0.0.0.0:4200"
        target: "_blank" # optional html a tag target attribute
      - name: "Portainer"
        logo: "docker.png"
        subtitle: "Docker"
        tag: "app"
        url: "https://0.0.0.0:9000"
        target: "_blank"  
  - name: "Apps"
    icon: "fas fa-cloud"
    items:
      - name: "Pi-Hole"
        logo: "pi-hole.png"
        subtitle: "Ad Blocking"
        tag: "app"
        url: "http://0.0.0.0:80/admin"
        target: "_blank" # optional html a tag target attribute
      - name: "BitWarden"
        logo: "bitwarden.png"
        subtitle: "Password Manager"
        tag: "app"
        url: "https://0.0.0.0:8443/"
        target: "_blank"      
        
